version: '3.8'

services:
  api:
    build: ./src/InventoryHold.WebApi
    ports:
      - "5000:80"
    depends_on:
      - mongo
      - redis
      - rabbitmq

  mongo:
    image: mongo

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
